/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class common_BarcodePrint */

#ifndef _Included_common_BarcodePrint
#define _Included_common_BarcodePrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     common_BarcodePrint
 * Method:    BarcodePrint
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_common_BarcodePrint_BarcodePrint
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
